# Generated by Django 3.0.4 on 2020-03-18 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('cId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=500)),
                ('taxNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('dId', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=500)),
                ('IsDelivered', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pId', models.AutoField(primary_key=True, serialize=False)),
                ('isActive', models.NullBooleanField()),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('cost', models.FloatField()),
                ('name', models.CharField(max_length=50)),
                ('modelNo', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('warrantyStatus', models.IntegerField()),
                ('disturbuterInfo', models.CharField(max_length=100)),
                ('categoryName', models.CharField(max_length=50)),
                ('listedDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('fId', models.AutoField(primary_key=True, serialize=False)),
                ('cId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_store.Client')),
                ('pId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_store.Product')),
            ],
            options={
                'unique_together': {('fId', 'cId')},
            },
        ),
        migrations.AddField(
            model_name='client',
            name='fId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_store.Favourite'),
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('bId', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('totalPrice', models.FloatField()),
                ('purchasedDate', models.DateField()),
                ('isPurchased', models.NullBooleanField(verbose_name=False)),
                ('cId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_store.Client')),
                ('pId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_store.Product')),
            ],
            options={
                'unique_together': {('bId', 'cId')},
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('iId', models.AutoField(primary_key=True, serialize=False)),
                ('bId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_store.Basket')),
                ('cId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_store.Client')),
                ('dId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_store.Delivery')),
            ],
            options={
                'unique_together': {('iId', 'bId', 'dId', 'cId')},
            },
        ),
    ]
