# Generated by Django 3.0.4 on 2020-04-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
