# Generated by Django 3.0.4 on 2020-03-18 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='fId',
        ),
    ]
