# Generated by Django 3.0.4 on 2020-04-27 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rId', models.AutoField(primary_key=True, serialize=False)),
                ('waitingForApproval', models.NullBooleanField()),
                ('Approved', models.NullBooleanField()),
                ('cId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_store.Customer')),
                ('pId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_store.Product')),
            ],
        ),
    ]
