# Generated by Django 3.0.4 on 2020-04-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='commentHeader',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='commentbody',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
