# Generated by Django 3.0.4 on 2020-04-24 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0004_auto_20200423_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='oId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_store.Order'),
        ),
    ]
