# Generated by Django 3.0.4 on 2020-04-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0005_address_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='location',
            new_name='address',
        ),
        migrations.AddField(
            model_name='images',
            name='imgSrc',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
