# Generated by Django 3.0.4 on 2020-05-10 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0009_auto_20200506_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='pId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productRating', to='online_store.Product'),
        ),
    ]
