# Generated by Django 3.0.4 on 2020-05-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0010_auto_20200510_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='displayOldPrice',
            field=models.NullBooleanField(),
        ),
    ]
