# Generated by Django 3.0.4 on 2020-05-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0011_product_displayoldprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='displayOldPrice',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
