# Generated by Django 3.0.4 on 2020-05-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0013_auto_20200510_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='sex',
        ),
        migrations.AddField(
            model_name='account',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='sex',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
